Repository SWE-574-Group-4/Community-Management-System, pull requests merged in 2024-11, with the labels that each got.

#118 #55 Fix Terms and Conditions button does not work
  client/src/components/template/Footer.tsx
  client/src/configs/routes.config/routes.config.ts
  client/src/views/UserAgreements/TermsAndConditions.tsx
Labels: bug, frontend

#125 [#56] Fix privacy policy button does not work
  client/src/components/template/Footer.tsx
  client/src/configs/routes.config/routes.config.ts
  client/src/views/UserAgreements/PrivacyPolicy.tsx
Labels: bug, frontend

#117 52 when the post is created the fields do not have headings
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/views/community/components/PostsTable.tsx
  client/src/views/post/components/DisplayPost.tsx
  server/.gitignore
  server/requirements.txt
Labels: bug, frontend

#119 #36 private communities are not visible at home page
  client/src/services/PostService.ts
  client/src/views/Home.tsx
  client/src/views/community/components/RecentCommunities.tsx
  server/communiche/views.py
Labels: bug, effort(Medium), frontend

#129 #98 DoB fixes & #59 Remove Password Mechanism.
  client/src/@types/auth.ts
  client/src/@types/community.ts
  client/src/@types/user.ts
  client/src/configs/routes.config/authRoute.tsx
  client/src/locales/lang/en.json
  client/src/services/AuthService.ts
  client/src/services/UserService.ts
  client/src/store/slices/auth/userSlice.ts
  client/src/utils/hooks/useAuth.ts
  client/src/views/account/Settings/components/Profile.tsx
  client/src/views/auth/ForgotPassword/ForgotPassword.tsx
  client/src/views/auth/ForgotPassword/ForgotPasswordForm.tsx
  client/src/views/auth/ForgotPassword/index.tsx
  client/src/views/auth/SignIn/SignInForm.tsx
  client/src/views/auth/SignUp/SignUpForm.tsx
  client/src/views/profile/Profile.tsx
Labels: bug, frontend, backend

#141 84 reporting an abuse as a member
  client/src/@types/post.ts
  client/src/@types/reports.ts
  client/src/configs/routes.config/routes.config.ts
  client/src/services/ReportService.ts
  client/src/views/community/CommunityDetail.tsx
  client/src/views/community/components/Reports.tsx
  client/src/views/community/components/ReportsTable.tsx
  client/src/views/post/components/Comment.tsx
  client/src/views/post/components/DisplayPost.tsx
  client/src/views/report/CreateReport.tsx
  client/src/views/report/ReportView.tsx
  server/communiche/migrations/0036_report.py
  server/communiche/migrations/0037_alter_report_user.py
  server/communiche/migrations/0038_remove_report_reported_user.py
  server/communiche/migrations/0039_report_status.py
  server/communiche/models.py
  server/communiche/serializers.py
  server/communiche/settings.py
  server/communiche/urls.py
  server/communiche/views.py
  server/requirements.txt
Labels: Feature request, frontend, backend

#137 68 earning system wide badges
  client/public/img/badges/community_leader.png
  client/public/img/badges/contributor.png
  client/public/img/badges/influencer.png
  client/public/img/badges/popular_post.png
  client/public/img/badges/veteran.png
  client/src/@types/user.ts
  client/src/components/template/UserDropdown.tsx
  client/src/locales/lang/en.json
  client/src/services/BadgeService.ts
  client/src/services/UserService.ts
  client/src/views/account/Settings/Settings.tsx
  client/src/views/account/Settings/components/Badges.tsx
  client/src/views/account/Settings/components/BadgesTable.tsx
  client/src/views/account/Settings/components/Notifications.tsx
  client/src/views/account/Settings/components/NotificationsTable.tsx
  server/communiche/media/default_icon.png
  server/communiche/migrations/0036_badge_userbadge.py
  server/communiche/migrations/0037_notification.py
  server/communiche/migrations/0038_auto_20241112_1257.py
  server/communiche/migrations/0039_alter_badge_id.py
  server/communiche/migrations/0040_auto_20241124_0926.py
  server/communiche/migrations/0041_auto_20241124_1005.py
  server/communiche/models.py
  server/communiche/serializers.py
  server/communiche/settings.py
  server/communiche/urls.py
  server/communiche/views.py
  server/requirements.txt
Labels: enhancement, effort(Difficult), database, frontend, backend

#163 Fix report page breakpoint resizing error
  client/src/views/report/CreateReport.tsx
Labels: bug, effort(Easy), frontend
